
runtime: java
env: flex

runtime_config:
  jdk: openjdk8
  
handlers:
- url: /.*
  script: this field is required, but ignored
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  
beta_settings:
    cloud_sql_instances: rosy-griffin-253215:us-central1:pruebapost

  
